
# This file configures your Netlify deploy
# Settings declared here override everything on Dashboard interface
# https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  command = "npm run build"
  functions = "lambda"


# redirects with status 200 are rewrites
[[redirects]]
  from = "/"
  to = "/.netlify/functions/tweet"
  status = 200

